server {
    listen 80;
    location /instagram {
        proxy_pass http://backend:3000/instagram;
        proxy_set_header Host $host;
    }
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}